# Default values for gravitee-am.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

hostname: ""
mongodb_uri: "mongodb://mongo-mongodb-replicaset:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000"
